### Pipeline, step by step

In [472]:
import sys
import os
sys.path.append(os.getcwd())

import logging
import pandas as pd
from data_pipelines.filmladder import ScreeningScraper, ImdbIdScraper, RedirectUrlScraper
from data_pipelines.letterboxd import TmdbIdScraper
from data_pipelines.helpers import extract_unique_movies, get_new_movies
from backend.data_pipelines.helpers import process_cinemas, process_screenings
from backend.data_models.save_to_db import save_all_to_db
from rich import print

pd.options.display.max_rows = 100
pd.set_option('display.max_colwidth', None)
%load_ext autoreload
%autoreload 2

logging.basicConfig(level=logging.INFO)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

### Collect screenings

In [473]:
logging.info("Starting daily data pipeline...")

# 1️⃣ Scrape Filmladder (returns two DataFrames)
screening_scraper = ScreeningScraper()
screenings_df, cinemas_df = await screening_scraper.run()

INFO:root:Starting daily data pipeline...

### Remove duplicate screenings and process cinemas

In [474]:
# 2️⃣ Remove duplicates (imax, 2d, etc), add unique ids
screenings_df = process_screenings(screenings_df)
cinemas_df = process_cinemas(cinemas_df)

### Fetch ticket destination url

In [475]:
redirect_scraper = RedirectUrlScraper(cache_expiry=3600*24*7)
screenings_with_redirects = await redirect_scraper.run(screenings_df[10:20])

# TODO: SAVE SCREENINGS NOW

Cache hit for https://www.filmladder.nl/kaartjes/1209227400 - (scraper:a253b73a034f68fa1204743911836b1b)
Cache hit for https://www.filmladder.nl/kaartjes/1209228447 - (scraper:e083fcf639c3f59a225efd75ecdfd7b1)

### Extract unique titles from screenings, then visit each page to fetch corresponding IMDB ID

In [486]:
scraped_movies = extract_unique_movies(screenings_df)
imdb_id_scraper = ImdbIdScraper(cache_expiry=3600*24*7)
scraped_movies_with_id = await imdb_id_scraper.run(scraped_movies)

Cache hit for https://www.filmladder.nl/film/a-complete-unknown-2024/popup/amsterdam - (scraper:031ee0675d59d1820d3359c3f59f1a9d)
Cache hit for https://www.filmladder.nl/film/fiore-mio-2024/popup/amsterdam - (scraper:15f3a80ad34d7e40f91704ee5a7ed1ed)
Cache hit for https://www.filmladder.nl/film/all-we-imagine-as-light-2024/popup/amsterdam - (scraper:bea0533a887998a78b0dd2b3b5bb16a7)
Cache hit for https://www.filmladder.nl/film/hard-truths-2024/popup/amsterdam - (scraper:8f700edacb77cf28b18bd9ccb4ab5453)
Cache hit for https://www.filmladder.nl/film/anora-2024/popup/amsterdam - (scraper:d6f8c7e17508b7af1e628ee80bd2b6fc)
Cache hit for https://www.filmladder.nl/film/batman-begins-2005/popup/amsterdam - (scraper:76086bbe26538f094beef0aa4475051d)
Cache hit for https://www.filmladder.nl/film/bridget-jones-mad-about-the-boy-2025/popup/amsterdam - (scraper:807d3cd1d86728f42e7711bb0c2595b1)
Cache hit for https://www.filmladder.nl/film/en-fanfare-2024/popup/amsterdam - (scraper:7847ddd6112440b2cfb98c38d0ee36da)
Cache hit for https://www.filmladder.nl/film/everybody-loves-touda-2024/popup/amsterdam - (scraper:b6cc1ba26b8aec5c177d241e497e7888)
Cache hit for https://www.filmladder.nl/film/i-m-still-here-2024/popup/amsterdam - (scraper:b5f521c148acb6984a011603775c9ce2)
Cache hit for https://www.filmladder.nl/film/parthenope-2024/popup/amsterdam - (scraper:a3ff89eeac35c47b9084b296b79a819f)
Cache hit for https://www.filmladder.nl/film/september-5-2024/popup/amsterdam - (scraper:4df6e9b984657578d23ce2aa78c1c4df)
Cache hit for https://www.filmladder.nl/film/september-says-2024/popup/amsterdam - (scraper:0647a0452480ba84f669b35c14bf13f6)
Cache hit for https://www.filmladder.nl/film/the-brutalist-2024/popup/amsterdam - (scraper:1dc19ca224010bfa26eabf5f14b7f753)
Cache hit for https://www.filmladder.nl/film/the-last-journey-2024/popup/amsterdam - (scraper:254f35531ea82acdeeac59c23d28b748)
Cache hit for https://www.filmladder.nl/film/the-most-precious-of-cargoes-2024/popup/amsterdam - (scraper:5b8cdd5aa9076c7a3fbc5f4bdf8d26ec)
Cache hit for https://www.filmladder.nl/film/vermiglio-2024/popup/amsterdam - (scraper:8a7aa12ef46bf1903c621df07e0211a5)
Cache hit for https://www.filmladder.nl/film/amal-2023/popup/amsterdam - (scraper:1620a272762255a5fab15ea0550c7153)
Cache hit for https://www.filmladder.nl/film/brandweerman-sam-de-grote-show-2024/popup/amsterdam - (scraper:ff8208b31e7d3bd9de55b46c101a6083)
Cache hit for https://www.filmladder.nl/film/crossing-istanbul-2024/popup/amsterdam - (scraper:bed35add10d4eba50daab0dc5c33c6c3)
Cache hit for https://www.filmladder.nl/film/de-idylle-2025/popup/amsterdam - (scraper:d0b90b89acdb2f8f9f78d4fb3da8277b)
Cache hit for https://www.filmladder.nl/film/disney-snow-white-nl-2025/popup/amsterdam - (scraper:c8ad44d370c13f4573cbf7094666761f)
Cache hit for https://www.filmladder.nl/film/disney-s-snow-white-ov-2025/popup/amsterdam - (scraper:8b4027bf64bb16b190f0ed2893242e4a)
Cache hit for https://www.filmladder.nl/film/et-maintenant-on-va-ou-2011/popup/amsterdam - (scraper:b95e3672116ae38df30c4bd1aecfd9ff)
Cache hit for https://www.filmladder.nl/film/how-to-make-millions-before-grandma-dies-2024/popup/amsterdam - (scraper:b7fea3a1d94044bdce1b45de5a1ea4a1)
Cache hit for https://www.filmladder.nl/film/kneecap-2024/popup/amsterdam - (scraper:f4208880164723d0b567a6ef7204f100)
Cache hit for https://www.filmladder.nl/film/la-prisonniere-de-bordeaux-2024/popup/amsterdam - (scraper:763eddabb5e8aaf0fb73a4f1551b7088)
Cache hit for https://www.filmladder.nl/film/mickey-17-2025/popup/amsterdam - (scraper:7a5d9f953a054388f4f68e84cc84cfad)
Cache hit for https://www.filmladder.nl/film/mr-k-2024/popup/amsterdam - (scraper:ddef650e2a5fd5391307811cbe38cfe3)
Cache hit for https://www.filmladder.nl/film/mufasa-the-lion-king-nl-2024/popup/amsterdam - (scraper:1912220f20c078999eaf429d4a913442)
Cache hit for https://www.filmladder.nl/film/no-other-land-2024/popup/amsterdam - (scraper:e3351b41454efa6bf5a3ae541d724d92)
Cache hit for https://www.filmladder.nl/film/nosferatu-2024/popup/amsterdam - (scraper:7580f8ccb900916bac2133ca3c7735b3)
Cache hit for https://www.filmladder.nl/film/one-of-them-days-2025/popup/amsterdam - (scraper:1dd7e9139294ea33f48731e335bdabac)
Cache hit for https://www.filmladder.nl/film/paddington-in-peru-ov-2024/popup/amsterdam - (scraper:52cd3b40975b73b10719d7270f205564)
Cache hit for https://www.filmladder.nl/film/sing-sing-2024/popup/amsterdam - (scraper:718ea903998d1c41bb1206844b528240)
Cache hit for https://www.filmladder.nl/film/straatcoaches-vs-aliens-2024/popup/amsterdam - (scraper:8d08f67fa53e32c9981f4230f1ed8859)
Cache hit for https://www.filmladder.nl/film/the-seed-of-the-sacred-fig-2024/popup/amsterdam - (scraper:947853e3d4c79c871ec89d524cf418b0)
Cache hit for https://www.filmladder.nl/film/wadjda-2012/popup/amsterdam - (scraper:babff24c40edaed2d3ef6944ce28541c)
Cache hit for https://www.filmladder.nl/film/becoming-led-zeppelin-2025/popup/amsterdam - (scraper:8a172e96e201013c02f26015b0a16a12)
Cache hit for https://www.filmladder.nl/film/ernest-cole-lost-and-found-2024/popup/amsterdam - (scraper:6a27bf282d760a300cd638f6852d4b8a)
Cache hit for https://www.filmladder.nl/film/favoriten-2024/popup/amsterdam - (scraper:6f35b1e72f8f81f77e64f4909e1723bf)
Cache hit for https://www.filmladder.nl/film/half-moon-2024/popup/amsterdam - (scraper:29a52c6965d33aacc68d1fafc29686c8)
Cache hit for https://www.filmladder.nl/film/metamorfose-2023/popup/amsterdam - (scraper:3062ee251652b793229d9593a4900279)
Cache hit for https://www.filmladder.nl/film/nesjomme-2024/popup/amsterdam - (scraper:067d162ea84f91b4ba1c104c01dadce3)
Cache hit for https://www.filmladder.nl/film/sujo-2024/popup/amsterdam - (scraper:24b2dc21cab44b0fe2c6fe5fc5d5307c)
Cache hit for https://www.filmladder.nl/film/the-invasion-2024/popup/amsterdam - (scraper:f577a67a13586d512c2b4baa02ade035)
Cache hit for https://www.filmladder.nl/film/conclave-2024/popup/amsterdam - (scraper:3a57e4917a3d3c8ede10a3fbcfbb6968)
Cache hit for https://www.filmladder.nl/film/flow-2024/popup/amsterdam - (scraper:bb073145b941eaec484d20da117a4f24)
Cache hit for https://www.filmladder.nl/film/hoe-te-verdwijnen-2024/popup/amsterdam - (scraper:e1b9803769491ec24ef8ce20b342edce)
Cache hit for https://www.filmladder.nl/film/la-grande-bellezza-2013/popup/amsterdam - (scraper:87adbbb07b81529da262abcf613901ff)
Cache hit for https://www.filmladder.nl/film/la-haine-1995/popup/amsterdam - (scraper:68ac584772faeb7d8362ee5e54df9b85)
Cache hit for https://www.filmladder.nl/film/les-quatre-cents-coups-1959-47316/popup/amsterdam - (scraper:0c0660263974993ee56ff3f6de0b0770)
Cache hit for https://www.filmladder.nl/film/madeliefjes-1966/popup/amsterdam - (scraper:fcaaf2c25da9ebdb6d5b543c806a04f6)
Cache hit for https://www.filmladder.nl/film/memoir-of-a-snail-2024/popup/amsterdam - (scraper:5ba81998d1ee1d5e25e0dbeaf79c9476)
Cache hit for https://www.filmladder.nl/film/primer-2004/popup/amsterdam - (scraper:83a45c21e1f4fd07f4ec38fc6602c12d)
Cache hit for https://www.filmladder.nl/film/spring-summer-fall-winter-and-spring-2003/popup/amsterdam - (scraper:d417c77ebf87a1ef2fc47bbf0b974b70)
Cache hit for https://www.filmladder.nl/film/alpha-2024/popup/amsterdam - (scraper:3474f92ba89e1a9521b6d0ca95d2ad47)
Cache hit for https://www.filmladder.nl/film/caught-by-the-tides-2024/popup/amsterdam - (scraper:ab72199b739e361d8910d0df9e4d1695)
Cache hit for https://www.filmladder.nl/film/de-spiegel-1975/popup/amsterdam - (scraper:81a4b17735d0d6598eecc6e47dda1aad)
Cache hit for https://www.filmladder.nl/film/grand-tour-2024/popup/amsterdam - (scraper:223ecb8540de42c596586cd1b548daad)
Cache hit for https://www.filmladder.nl/film/kasaba-1997/popup/amsterdam - (scraper:31e0cad57c035745e65887e6dad47e86)
Cache hit for https://www.filmladder.nl/film/la-negra-angustias-1950/popup/amsterdam - (scraper:929a15cb9c71ac03ebad9de7117cdd5c)
Cache hit for https://www.filmladder.nl/film/maria-2024/popup/amsterdam - (scraper:3998ef3d96dcf14599ac121f164a431b)
Cache hit for https://www.filmladder.nl/film/misericorde-2024/popup/amsterdam - (scraper:1f5c0caddca44037f365d27ab0ce822b)
Cache hit for https://www.filmladder.nl/film/naplo-diary-for-my-children-1984/popup/amsterdam - (scraper:c4500982ad981a92f665c9bc60d35b0f)
Cache hit for https://www.filmladder.nl/film/once-upon-a-time-in-anatolia-2011/popup/amsterdam - (scraper:1c594fd9f8552625b5681611209661eb)
Cache hit for https://www.filmladder.nl/film/picknick-met-taart-2012/popup/amsterdam - (scraper:3efe17a8b8ed8db1124dd180212cc95c)
Cache hit for https://www.filmladder.nl/film/red-de-jungle-2024/popup/amsterdam - (scraper:af69e544bcea42bbd681711cd4f62ac2)
Cache hit for https://www.filmladder.nl/film/secrets-lies-1996/popup/amsterdam - (scraper:6e49ede80298870d1d4c2798a4108531)
Cache hit for https://www.filmladder.nl/film/the-motorcycle-diaries-2004/popup/amsterdam - (scraper:ad21b262c41ac4a5aea2628953e142c5)
Cache hit for https://www.filmladder.nl/film/the-piano-1993/popup/amsterdam - (scraper:41fab70f5905b9c6992c1c162851c973)
Cache hit for https://www.filmladder.nl/film/uzak-2002/popup/amsterdam - (scraper:ffacbca2ba36cb6febc9ae05af240704)
Cache hit for https://www.filmladder.nl/film/winter-sleep-2014/popup/amsterdam - (scraper:5d3b7c4a048a1fc0555bbe6af0d28cf6)
Cache hit for https://www.filmladder.nl/film/dikkie-dik-2-een-nieuwe-vriend-voor-dikkie-dik-2024/popup/amsterdam - (scraper:3ef485d220994888bfa0947ed5132cee)
Cache hit for https://www.filmladder.nl/film/paddington-in-peru-nl-2024/popup/amsterdam - (scraper:2291e2304632b4364075812649e1d6cf)
Cache hit for https://www.filmladder.nl/film/a-real-pain-2024/popup/amsterdam - (scraper:1bfd3cc041c70085ac2cc9a0b53694b4)
Cache hit for https://www.filmladder.nl/film/apocalypse-now-final-cut-1979-199302/popup/amsterdam - (scraper:c2f05b1c080e0280bd80a655edbb9d51)
Cache hit for https://www.filmladder.nl/film/babygirl-2024/popup/amsterdam - (scraper:01ab9d4df1411ddb74dfcaa86705f953)
Cache hit for https://www.filmladder.nl/film/giant-1956/popup/amsterdam - (scraper:b5fb6a2df2420469963ccf87a158d563)
Cache hit for https://www.filmladder.nl/film/gilda-1946/popup/amsterdam - (scraper:c56e7ed7d8646786023c4833f0d426e6)
Cache hit for https://www.filmladder.nl/film/i-am-not-a-robot-2023/popup/amsterdam - (scraper:40bb213581bf0be9fa35427724b50794)
Cache hit for https://www.filmladder.nl/film/looney-tunes-the-day-the-earth-blew-up-nl-2024/popup/amsterdam - (scraper:590c30a0b4f7ebc26b7535cc011b0214)
Cache hit for https://www.filmladder.nl/film/my-sunshine-2024/popup/amsterdam - (scraper:8d297c9010fd61ffac0e9f88f0e13564)
Cache hit for https://www.filmladder.nl/film/queer-2024/popup/amsterdam - (scraper:ba5149eb6f98a7e9d6934a9ce956f6d7)
Cache hit for https://www.filmladder.nl/film/saving-private-ryan-1998/popup/amsterdam - (scraper:14bb8ef8a745c2e11a2c24c136c7af44)
Cache hit for https://www.filmladder.nl/film/the-substance-2024/popup/amsterdam - (scraper:04b9fbe4729566c2b37f574829179fc0)
Cache hit for https://www.filmladder.nl/film/la-pampa-2024/popup/amsterdam - (scraper:2e2c666c7ba97660e4e649c38d3b95ca)
Cache hit for https://www.filmladder.nl/film/pas-de-vagues-2024/popup/amsterdam - (scraper:720c758abebc4373aa4d7f567b2aba62)
Cache hit for https://www.filmladder.nl/film/vivre-mourir-renaitre-2024/popup/amsterdam - (scraper:1325f06ffb512951c1cdca2abd35a08f)
Cache hit for https://www.filmladder.nl/film/woezel-pip-op-avontuur-in-de-tovertuin-2025/popup/amsterdam - (scraper:0cbfb7a3991e0b11e4dd929f919c1648)
Cache hit for https://www.filmladder.nl/film/belle-de-jour-1967/popup/amsterdam - (scraper:4d8661c66436e3f3b8c8fd6853541a08)
Cache hit for https://www.filmladder.nl/film/dead-lover-2025/popup/amsterdam - (scraper:c76380574988c025462799d1bc5e55c9)
Cache hit for https://www.filmladder.nl/film/funeral-parade-of-roses-1969/popup/amsterdam - (scraper:1f8258fb7770e047968e4d7a20880ac3)
Cache hit for https://www.filmladder.nl/film/mamma-roma-1962/popup/amsterdam - (scraper:89e2230bfa1df03ede8ab915129d27ae)
Cache hit for https://www.filmladder.nl/film/manas-2024/popup/amsterdam - (scraper:446b508c9517f50f7cf64d7caa933de0)
Cache hit for https://www.filmladder.nl/film/pippi-zet-de-boel-op-stelten-1970/popup/amsterdam - (scraper:ec28766ad42d604b63145ccad57d989c)
Cache hit for https://www.filmladder.nl/film/the-discreet-charm-of-the-bourgeoisie-1972/popup/amsterdam - (scraper:72bdb78eab96bb72ba803af2c14b3d58)
Cache hit for https://www.filmladder.nl/film/when-the-light-breaks-2024/popup/amsterdam - (scraper:7b87cd0a23ba0fdc3b25164a5db0e257)
Cache hit for https://www.filmladder.nl/film/atlantique-2019/popup/amsterdam - (scraper:3bb75829e22c0b22994ce3deee8c1113)
Cache hit for https://www.filmladder.nl/film/eraserhead-1977/popup/amsterdam - (scraper:44e056abdba66f3f9f41ec4ea8868179)
Cache hit for https://www.filmladder.nl/film/lost-highway-1997/popup/amsterdam - (scraper:a026e7011ce732601521cd4ae1f00492)
Cache hit for https://www.filmladder.nl/film/mississippi-burning-1988/popup/amsterdam - (scraper:d225a9a85205d6d1eba348a9ab0684d2)
Cache hit for https://www.filmladder.nl/film/mulholland-drive-2001/popup/amsterdam - (scraper:e4cfb014d8b54ac91221e58ead69cbdf)
Cache hit for https://www.filmladder.nl/film/mustang-2015/popup/amsterdam - (scraper:01f710f6b51413c77d7cca9ab4505753)
Cache hit for https://www.filmladder.nl/film/parasite-2019/popup/amsterdam - (scraper:5543c5231fcbe96be9cb787de9ee7000)
Cache hit for https://www.filmladder.nl/film/paris-texas-1984/popup/amsterdam - (scraper:c09437d8d9dbd8839551d12dcf64e09f)
Cache hit for https://www.filmladder.nl/film/past-lives-2023/popup/amsterdam - (scraper:ef0c1c2fc2b0c64c72a0ac92d3807e3b)
Cache hit for https://www.filmladder.nl/film/picnic-at-hanging-rock-1975/popup/amsterdam - (scraper:1590090b14fa5364da2d9585e162f22a)
Cache hit for https://www.filmladder.nl/film/snowpiercer-2013/popup/amsterdam - (scraper:f442225501159c9da0e6da0b3e82b4c3)
Cache hit for https://www.filmladder.nl/film/the-apartment-1960/popup/amsterdam - (scraper:8159e2ac6a01a50dcbf290813253270d)
Cache hit for https://www.filmladder.nl/film/the-big-lebowski-1998/popup/amsterdam - (scraper:28845009ffa9b0987aa6c7dcafa2aaad)
Cache hit for https://www.filmladder.nl/film/the-birdcage-1996/popup/amsterdam - (scraper:8ce08d26107f8cdf87432366326a6843)
Cache hit for https://www.filmladder.nl/film/the-conversation-1974-410831/popup/amsterdam - (scraper:8a0fa3b2df3fe1aa9b380d32bfd507a3)
Cache hit for https://www.filmladder.nl/film/titane-2021/popup/amsterdam - (scraper:377552467d147f6e1666479be9f24f1b)
Cache hit for https://www.filmladder.nl/film/twin-peaks-fire-walk-with-me-1992/popup/amsterdam - (scraper:591cdec2115fb6535e23aed7a248f246)
Cache hit for https://www.filmladder.nl/film/unforgiven-1992/popup/amsterdam - (scraper:fb9b0096402f4fe121c3f973228f10bc)
Cache hit for https://www.filmladder.nl/film/wild-at-heart-1990/popup/amsterdam - (scraper:3ad883c3d2e2092fe86b93ff4cab2661)
Cache hit for https://www.filmladder.nl/film/summer-wars-2009/popup/amsterdam - (scraper:c0cc52022808619ee32b7b731c45dbc4)
Cache hit for https://www.filmladder.nl/film/aftermath-2024/popup/amsterdam - (scraper:9d96dd3b5e7fd237a01ff75aa2ebf4af)
Cache hit for https://www.filmladder.nl/film/attack-on-titan-the-last-attack-2024/popup/amsterdam - (scraper:30d6cee1bf53c0b6fd85dd69cd7abe6e)
Cache hit for https://www.filmladder.nl/film/captain-america-brave-new-world-2025/popup/amsterdam - (scraper:a5327c7bc7df5c63820d32124327f973)
Cache hit for https://www.filmladder.nl/film/hans-zimmer-friends-diamond-in-the-desert-2025/popup/amsterdam - (scraper:cea408c271f90daab72192c8813265ab)
Cache hit for https://www.filmladder.nl/film/juffrouw-pots-2024/popup/amsterdam - (scraper:2e13b59f1a1998311bca22d9e18f3f57)
Cache hit for https://www.filmladder.nl/film/k3-en-het-lied-van-de-zeemeermin-2024/popup/amsterdam - (scraper:69572bc1365094f847f494ccf7bb9fb5)
Cache hit for https://www.filmladder.nl/film/last-breath-2024/popup/amsterdam - (scraper:271d5baac19f25a3bf7fc8a8ace79f42)
Cache hit for https://www.filmladder.nl/film/mufasa-the-lion-king-ov-2024/popup/amsterdam - (scraper:380dc5751eb80a81e677d81d5b09ec37)
Cache hit for https://www.filmladder.nl/film/novocaine-2025/popup/amsterdam - (scraper:0568b69042bf39279c21c561f10c2788)
Cache hit for https://www.filmladder.nl/film/patsers-2025/popup/amsterdam - (scraper:537cda432b3d059ecf108c386a05416d)
Cache hit for https://www.filmladder.nl/film/rebellious-2024/popup/amsterdam - (scraper:a4906b80beadedbadbfc60fe85f3a818)
Cache hit for https://www.filmladder.nl/film/small-things-like-these-2024/popup/amsterdam - (scraper:3f1e7710078c26ee1ac36edea133111e)
Cache hit for https://www.filmladder.nl/film/sonic-the-hedgehog-3-nl-2024/popup/amsterdam - (scraper:2903f5353ca2b0bbf301cd012fd918a4)
Cache hit for https://www.filmladder.nl/film/the-monkey-2025/popup/amsterdam - (scraper:0e77bee6ad05b1e33aebcde2f2c1c6b6)
Cache hit for https://www.filmladder.nl/film/vaiana-2-nl-2024/popup/amsterdam - (scraper:d3bb5231e7113e688143b19dad613bee)
Cache hit for https://www.filmladder.nl/film/den-of-thieves-pantera-2025/popup/amsterdam - (scraper:3519dd7bd4a80c4a0517afd55c65b95c)
Cache hit for https://www.filmladder.nl/film/flight-risk-2024/popup/amsterdam - (scraper:99a7670abdc8e8d7aa65dcbd59c39dc4)
Cache hit for https://www.filmladder.nl/film/sonic-the-hedgehog-3-ov-2024/popup/amsterdam - (scraper:596aa68b2539ffe53a6227398a2ccd4b)
Cache hit for https://www.filmladder.nl/film/william-tell-2024/popup/amsterdam - (scraper:1acd4f973f3b669f0ba05e43724c5aeb)
Cache hit for https://www.filmladder.nl/film/the-return-2024/popup/amsterdam - (scraper:a4bc24eb8361dee2ebeb6503220dea86)
Cache hit for https://www.filmladder.nl/film/the-untouchables-1987/popup/amsterdam - (scraper:bca086e5e58d7d6f38964657853ae825)
Cache hit for https://www.filmladder.nl/film/companion-2025/popup/amsterdam - (scraper:3c7015da4d4fe59f39ac9ff4d707ef94)
Cache hit for https://www.filmladder.nl/film/interstellar-2014/popup/amsterdam - (scraper:3343f92065f7436f2c432e6103866a16)
Cache hit for https://www.filmladder.nl/film/we-live-in-time-2024/popup/amsterdam - (scraper:04b63403c2938523379bdca84d8c2746)
Cache hit for https://www.filmladder.nl/film/wicked-ov-2024/popup/amsterdam - (scraper:c62e841d034861f847e5de169e40fa16)
Cache hit for https://www.filmladder.nl/film/goodfellas-1990/popup/amsterdam - (scraper:a6ebd42e1d1668d0c8b4fc66ad15f986)
Cache hit for https://www.filmladder.nl/film/the-godfather-part-ii-1974/popup/amsterdam - (scraper:c55233732f94e58b471fb88fc467fc71)
Cache hit for https://www.filmladder.nl/film/dahomey-2024/popup/amsterdam - (scraper:67e5039e75f5b98e4120252b47c4ba97)
Cache hit for https://www.filmladder.nl/film/de-propagandist-2025/popup/amsterdam - (scraper:c7ed0ac9b0084de3d06d8d8fbb15d42d)
Cache hit for https://www.filmladder.nl/film/iedereen-is-van-de-wereld-2024/popup/amsterdam - (scraper:8340fe82feb85b44a741f76c4ca26719)
Cache hit for https://www.filmladder.nl/film/inception-2010/popup/amsterdam - (scraper:c3105d7f1068cbcbdea5584d650dd2d1)
Cache hit for https://www.filmladder.nl/film/megalopolis-2024/popup/amsterdam - (scraper:644619c4fd6626c75826265f51abdbc1)
Cache hit for https://www.filmladder.nl/film/a-place-in-the-sun-1951/popup/amsterdam - (scraper:7c36100d5c4127907ad913937eeb6723)
Cache hit for https://www.filmladder.nl/film/from-here-to-eternity-1953/popup/amsterdam - (scraper:847fe70da44f6fd8034af2407b1bf7e6)
Cache hit for https://www.filmladder.nl/film/hair-1979/popup/amsterdam - (scraper:68ce55ccee423e3df4562778b24cfd04)
Cache hit for https://www.filmladder.nl/film/the-lady-from-shanghai-1947/popup/amsterdam - (scraper:ffe1c8ef9bd51d60d6bbb2c83cfb19fb)

### Use the fetched IMDB ID as a look up for which titles are not yet in the db and consequently, new

In [488]:
pd.set_option('display.width', 1000)
new_movies = get_new_movies(scraped_movies=scraped_movies_with_id)
new_movies

                             fl_title fl_year                                                                       fl_movie_link                              imdb_link     imdb_id
5                       batman begins    2005                   https://www.filmladder.nl/film/batman-begins-2005/popup/amsterdam   https://www.imdb.com/title/tt0372784   tt0372784
8               everybody loves touda    2024           https://www.filmladder.nl/film/everybody-loves-touda-2024/popup/amsterdam  https://www.imdb.com/title/tt29359373  tt29359373
12                     september says    2024                  https://www.filmladder.nl/film/september-says-2024/popup/amsterdam  https://www.imdb.com/title/tt29315015  tt29315015
18   brandweerman sam - de grote show    2024  https://www.filmladder.nl/film/brandweerman-sam-de-grote-show-2024/popup/amsterdam                                   None         NaN
41                          half moon    2024                       https://www.filmladder.nl/film/half-moon-2024/popup/amsterdam  https://www.imdb.com/title/tt35618593  tt35618593
42                        metamorfose    2023                     https://www.filmladder.nl/film/metamorfose-2023/popup/amsterdam  https://www.imdb.com/title/tt29959771  tt29959771
51             les quatre cents coups    None    https://www.filmladder.nl/film/les-quatre-cents-coups-1959-47316/popup/amsterdam   https://www.imdb.com/title/tt0053198   tt0053198
54                             primer    2004                          https://www.filmladder.nl/film/primer-2004/popup/amsterdam   https://www.imdb.com/title/tt0390384   tt0390384
61                 la negra angustias    1950              https://www.filmladder.nl/film/la-negra-angustias-1950/popup/amsterdam   https://www.imdb.com/title/tt0041686   tt0041686
80                   i am not a robot    2023                https://www.filmladder.nl/film/i-am-not-a-robot-2023/popup/amsterdam  https://www.imdb.com/title/tt19837932  tt19837932
86                           la pampa    2024                        https://www.filmladder.nl/film/la-pampa-2024/popup/amsterdam  https://www.imdb.com/title/tt32119317  tt32119317
88            vivre, mourir, renaître    2024           https://www.filmladder.nl/film/vivre-mourir-renaitre-2024/popup/amsterdam  https://www.imdb.com/title/tt30426575  tt30426575
144             the godfather part ii    1974           https://www.filmladder.nl/film/the-godfather-part-ii-1974/popup/amsterdam   https://www.imdb.com/title/tt0071562   tt0071562
146                   de propagandist    2025                 https://www.filmladder.nl/film/de-propagandist-2025/popup/amsterdam  https://www.imdb.com/title/tt29341054  tt29341054

### Get identifiers from Letterboxd (lb_id, tmdb_id, lb_film_slug)

In [493]:
# The following function visits the letterboxd page for each new film in the db and retrieves the lb slug and the TMDB id
tmdb_scraper = TmdbIdScraper(cache_expiry=3600*24*7)
new_movies_with_lb = await tmdb_scraper.run(new_movies)

/Users/ardsnijders/Documents/cineville_scraper/backend/data_pipelines/letterboxd.py:79: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['letterboxd_url'] = df['imdb_id'].apply(lambda x: build_url(x))

Cache hit for https://letterboxd.com/imdb/tt0372784 - (scraper:59ac716dd024802d94517e6e045c16d3)
Cache hit for https://letterboxd.com/imdb/tt29359373 - (scraper:13a8c50546d60063ba0fe103139e155e)
Cache hit for https://letterboxd.com/imdb/tt35618593 - (scraper:1f61da2091658bd1a31f36446bd09831)
Cache hit for https://letterboxd.com/imdb/nan - (scraper:e88a884ef1f6c53bde73783dd4fa004b)
Cache hit for https://letterboxd.com/imdb/tt29315015 - (scraper:93583e0ffd2d946b3841639c7bb0d2b3)
Cache hit for https://letterboxd.com/imdb/tt29959771 - (scraper:58abde2ed7090d0c4b362eb1db758e27)
Cache hit for https://letterboxd.com/imdb/tt0053198 - (scraper:3c6c0de5290d77357437b72c123209a6)
Cache hit for https://letterboxd.com/imdb/tt0390384 - (scraper:6e284f0db2a2809e0cece4dc31d1b9fd)
Cache hit for https://letterboxd.com/imdb/tt19837932 - (scraper:150185c0b7158517d3f1cafbb16d324c)
Cache hit for https://letterboxd.com/imdb/tt0041686 - (scraper:a56870778b3581c7509881dac64e8cd0)
Cache hit for https://letterboxd.com/imdb/tt32119317 - (scraper:6a40e49c39e18fed5ebd3e62e4f68807)
Cache hit for https://letterboxd.com/imdb/tt30426575 - (scraper:dfa54046dcb4cc25f1f9c09a3031407c)
Cache hit for https://letterboxd.com/imdb/tt0071562 - (scraper:ea211b4bd78642ed955350ffe1992ce2)
Cache hit for https://letterboxd.com/imdb/tt29341054 - (scraper:9ebc6c950f372b57846a0d687bce54c6)

In [494]:
new_movies_with_lb

                            fl_title fl_year                                                                       fl_movie_link                              imdb_link     imdb_id                          letterboxd_url  tmdb_id lb_film_id                  lb_film_slug                                  lb_poster_url
0                      batman begins    2005                   https://www.filmladder.nl/film/batman-begins-2005/popup/amsterdam   https://www.imdb.com/title/tt0372784   tt0372784   https://letterboxd.com/imdb/tt0372784      272      51784                 batman-begins                 /film/batman-begins/image-150/
1              everybody loves touda    2024           https://www.filmladder.nl/film/everybody-loves-touda-2024/popup/amsterdam  https://www.imdb.com/title/tt29359373  tt29359373  https://letterboxd.com/imdb/tt29359373  1246211    1129339         everybody-loves-touda         /film/everybody-loves-touda/image-150/
2                     september says    2024                  https://www.filmladder.nl/film/september-says-2024/popup/amsterdam  https://www.imdb.com/title/tt29315015  tt29315015  https://letterboxd.com/imdb/tt29315015  1212337    1096802                september-says                /film/september-says/image-150/
3   brandweerman sam - de grote show    2024  https://www.filmladder.nl/film/brandweerman-sam-de-grote-show-2024/popup/amsterdam                                    NaN         NaN         https://letterboxd.com/imdb/nan      NaN        NaN                           NaN                                            NaN
6                          half moon    2024                       https://www.filmladder.nl/film/half-moon-2024/popup/amsterdam  https://www.imdb.com/title/tt35618593  tt35618593  https://letterboxd.com/imdb/tt35618593      NaN        NaN                           NaN                                            NaN
7                        metamorfose    2023                     https://www.filmladder.nl/film/metamorfose-2023/popup/amsterdam  https://www.imdb.com/title/tt29959771  tt29959771  https://letterboxd.com/imdb/tt29959771      NaN        NaN                           NaN                                            NaN
8             les quatre cents coups     NaN    https://www.filmladder.nl/film/les-quatre-cents-coups-1959-47316/popup/amsterdam   https://www.imdb.com/title/tt0053198   tt0053198   https://letterboxd.com/imdb/tt0053198      147      51904                 the-400-blows                 /film/the-400-blows/image-150/
9                             primer    2004                          https://www.filmladder.nl/film/primer-2004/popup/amsterdam   https://www.imdb.com/title/tt0390384   tt0390384   https://letterboxd.com/imdb/tt0390384    14337       2682                        primer                        /film/primer/image-150/
10                la negra angustias    1950              https://www.filmladder.nl/film/la-negra-angustias-1950/popup/amsterdam   https://www.imdb.com/title/tt0041686   tt0041686   https://letterboxd.com/imdb/tt0041686   389644     324085            la-negra-angustias            /film/la-negra-angustias/image-150/
11                  i am not a robot    2023                https://www.filmladder.nl/film/i-am-not-a-robot-2023/popup/amsterdam  https://www.imdb.com/title/tt19837932  tt19837932  https://letterboxd.com/imdb/tt19837932  1178556    1065133           im-not-a-robot-2023           /film/im-not-a-robot-2023/image-150/
12                          la pampa    2024                        https://www.filmladder.nl/film/la-pampa-2024/popup/amsterdam  https://www.imdb.com/title/tt32119317  tt32119317  https://letterboxd.com/imdb/tt32119317  1001006     901780                    block-pass                    /film/block-pass/image-150/
13           vivre, mourir, renaître    2024           https://www.filmladder.nl/film/vivre-mourir-renaitre-2024/popup/amsterdam  https://www.imdb.com/title/tt30426575  tt30426575  https://letterboxd.com/imdb/tt30426575  1190698    1076633  to-live-to-die-to-live-again  /film/to-live-to-die-to-live-again/image-150/
14             the godfather part ii    1974           https://www.filmladder.nl/film/the-godfather-part-ii-1974/popup/amsterdam   https://www.imdb.com/title/tt0071562   tt0071562   https://letterboxd.com/imdb/tt0071562      240      51816         the-godfather-part-ii         /film/the-godfather-part-ii/image-150/
15                   de propagandist    2025                 https://www.filmladder.nl/film/de-propagandist-2025/popup/amsterdam  https://www.imdb.com/title/tt29341054  tt29341054  https://letterboxd.com/imdb/tt29341054  1374310    1260548              the-propagandist              /film/the-propagandist/image-150/

### Collect Metadata from TMDB using tmdb_id (movie_info, movie_keywords, movie_reviews)

In [496]:
from data_pipelines.tmdb import TMDBMetadataCollector
metadata_collector = TMDBMetadataCollector()
movies_with_metadata = await metadata_collector.run(df=new_movies_with_lb)

cache hit for tmdb id 389644 - (tmdb:389644)
cache hit for tmdb id 14337 - (tmdb:14337)
cache hit for tmdb id 1190698 - (tmdb:1190698)
cache hit for tmdb id 1374310 - (tmdb:1374310)
cache hit for tmdb id 240 - (tmdb:240)
cache hit for tmdb id 1178556 - (tmdb:1178556)
cache hit for tmdb id 1001006 - (tmdb:1001006)
cache hit for tmdb id 1246211 - (tmdb:1246211)
cache hit for tmdb id 1212337 - (tmdb:1212337)
cache hit for tmdb id 147 - (tmdb:147)
cache hit for tmdb id 272 - (tmdb:272)

In [497]:
movies_with_metadata

                            fl_title fl_year                                                                       fl_movie_link                              imdb_link     imdb_id                          letterboxd_url  tmdb_id lb_film_id                  lb_film_slug                                  lb_poster_url  \
0                      batman begins    2005                   https://www.filmladder.nl/film/batman-begins-2005/popup/amsterdam   https://www.imdb.com/title/tt0372784   tt0372784   https://letterboxd.com/imdb/tt0372784      272      51784                 batman-begins                 /film/batman-begins/image-150/
1              everybody loves touda    2024           https://www.filmladder.nl/film/everybody-loves-touda-2024/popup/amsterdam  https://www.imdb.com/title/tt29359373  tt29359373  https://letterboxd.com/imdb/tt29359373  1246211    1129339         everybody-loves-touda         /film/everybody-loves-touda/image-150/
2                     september says    2024                  https://www.filmladder.nl/film/september-says-2024/popup/amsterdam  https://www.imdb.com/title/tt29315015  tt29315015  https://letterboxd.com/imdb/tt29315015  1212337    1096802                september-says                /film/september-says/image-150/
3   brandweerman sam - de grote show    2024  https://www.filmladder.nl/film/brandweerman-sam-de-grote-show-2024/popup/amsterdam                                    NaN         NaN         https://letterboxd.com/imdb/nan      NaN        NaN                           NaN                                            NaN
4                          half moon    2024                       https://www.filmladder.nl/film/half-moon-2024/popup/amsterdam  https://www.imdb.com/title/tt35618593  tt35618593  https://letterboxd.com/imdb/tt35618593      NaN        NaN                           NaN                                            NaN
5                        metamorfose    2023                     https://www.filmladder.nl/film/metamorfose-2023/popup/amsterdam  https://www.imdb.com/title/tt29959771  tt29959771  https://letterboxd.com/imdb/tt29959771      NaN        NaN                           NaN                                            NaN
6             les quatre cents coups     NaN    https://www.filmladder.nl/film/les-quatre-cents-coups-1959-47316/popup/amsterdam   https://www.imdb.com/title/tt0053198   tt0053198   https://letterboxd.com/imdb/tt0053198      147      51904                 the-400-blows                 /film/the-400-blows/image-150/
7                             primer    2004                          https://www.filmladder.nl/film/primer-2004/popup/amsterdam   https://www.imdb.com/title/tt0390384   tt0390384   https://letterboxd.com/imdb/tt0390384    14337       2682                        primer                        /film/primer/image-150/
8                 la negra angustias    1950              https://www.filmladder.nl/film/la-negra-angustias-1950/popup/amsterdam   https://www.imdb.com/title/tt0041686   tt0041686   https://letterboxd.com/imdb/tt0041686   389644     324085            la-negra-angustias            /film/la-negra-angustias/image-150/
9                   i am not a robot    2023                https://www.filmladder.nl/film/i-am-not-a-robot-2023/popup/amsterdam  https://www.imdb.com/title/tt19837932  tt19837932  https://letterboxd.com/imdb/tt19837932  1178556    1065133           im-not-a-robot-2023           /film/im-not-a-robot-2023/image-150/
10                          la pampa    2024                        https://www.filmladder.nl/film/la-pampa-2024/popup/amsterdam  https://www.imdb.com/title/tt32119317  tt32119317  https://letterboxd.com/imdb/tt32119317  1001006     901780                    block-pass                    /film/block-pass/image-150/
11           vivre, mourir, renaître    2024           https://www.filmladder.nl/film/vivre-mourir-renaitre-2024/popup/amsterdam  https://www.imdb.com/title/tt30426575  tt30426575  https://letterboxd.com/imdb/tt30426575  1190698    1076633  to-live-to-die-to-live-again  /film/to-live-to-die-to-live-again/image-150/
12             the godfather part ii    1974           https://www.filmladder.nl/film/the-godfather-part-ii-1974/popup/amsterdam   https://www.imdb.com/title/tt0071562   tt0071562   https://letterboxd.com/imdb/tt0071562      240      51816         the-godfather-part-ii         /film/the-godfather-part-ii/image-150/
13                   de propagandist    2025                 https://www.filmladder.nl/film/de-propagandist-2025/popup/amsterdam  https://www.imdb.com/title/tt29341054  tt29341054  https://letterboxd.com/imdb/tt29341054  1374310    1260548              the-propagandist              /film/the-propagandist/image-150/

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 tmdb_info  \
0   {'adult': False, 'backdrop_path': '/ew5FcYiRhTYNJAkxoVPMNlCOdVn.jpg', 'belongs_to_collection': {'id': 263, 'name': 'The Dark Knight Collection', 'poster_path': '/ogyw5LTmL53dVxsppcy8Dlm30Fu.jpg', 'backdrop_path': '/xyhrCEdB4XRkelfVsqXeUZ6rLHi.jpg'}, 'budget': 150000000, 'genres': [{'id': 28, 'name': 'Action'}, {'id': 80, 'name': 'Crime'}, {'id': 18, 'name': 'Drama'}], 'homepage': 'https://www.warnerbros.com/movies/batman-begins/', 'id': 272, 'imdb_id': 'tt0372784', 'origin_country': ['US'], 'original_language': 'en', 'original_title': 'Batman Begins', 'overview': 'Driven by tragedy, billionaire Bruce Wayne dedicates his life to uncovering and defeating the corruption that plagues his home, Gotham City.  Unable to work within the system, he instead creates a new identity, a symbol of fear for the criminal underworld - The Batman.', 'popularity': 4.22, 'poster_path': '/4MpN4kIEqUjW8OPtOQJXlTdHiJV.jpg', 'production_companies': [{'id': 174, 'logo_path': '/zhD3hhtKB5qyv7ZeL4uLpNxgMVU.png', 'name': 'Warner Bros. Pictures', 'origin_country': 'US'}, {'id': 429, 'logo_path': '/4Y00XuSMuP1gimd0jP6JT57QbCI.png', 'name': 'DC', 'origin_country': 'US'}, {'id': 9996, 'logo_path': '/3tvBqYsBhxWeHlu62SIJ1el93O7.png', 'name': 'Syncopy', 'origin_country': 'GB'}, {'id': 923, 'logo_path': '/5UQsZrfbfG2dYJbx8DxfoTr2Bvu.png', 'name': 'Legendary Pictures', 'origin_country': 'US'}, {'id': 19231, 'logo_path': None, 'name': 'Patalex III Productions Limited', 'origin_country': ''}], 'production_countries': [{'iso_3166_1': 'GB', 'name': 'United Kingdom'}, {'iso_3166_1': 'US', 'name': 'United States of America'}], 'release_date': '2005-06-10', 'revenue': 374218673, 'runtime': 140, 'spoken_languages': [{'english_name': 'English', 'iso_639_1': 'en', 'name': 'English'}, {'english_name': 'Urdu', 'iso_639_1': 'ur', 'name': 'اردو'}, {'english_name': 'Mandarin', 'iso_639_1': 'zh', 'name': '普通话'}], 'status': 'Released', 'tagline': 'Evil fears the knight.', 'title': 'Batman Begins', 'video': False, 'vote_average': 7.711, 'vote_count': 21297}
1                                                                                                                                                                                                                                                                                                                              {'adult': False, 'backdrop_path': '/36xmdXPsiygSI6IBUcogOQ0KgK8.jpg', 'belongs_to_collection': None, 'budget': 0, 'genres': [{'id': 18, 'name': 'Drama'}, {'id': 10402, 'name': 'Music'}], 'homepage': '', 'id': 1246211, 'imdb_id': 'tt29359373', 'origin_country': ['BE', 'DK', 'FR', 'MA', 'NL', 'NO'], 'original_language': 'ar', 'original_title': 'غناء تودا', 'overview': 'Touda is a sheikha (traditional singer and dancer) who performs in dingy bars to make ends meet. But Touda has a passion. She struggles for her art to be recognized and to ensure a better future for her deaf-and-mute son Yassine.', 'popularity': 0.519, 'poster_path': '/f8TNfWJ7wTalPxdcl3QYOMaVLiu.jpg', 'production_companies': [{'id': 20219, 'logo_path': None, 'name': 'Les Films du Nouveau Monde', 'origin_country': 'FR'}, {'id': 58725, 'logo_path': '/yN5wFO8H8grMaIbxI1S2DoDLxyp.png', 'name': 'Ali'n Productions', 'origin_country': 'MA'}, {'id': 7117, 'logo_path': '/mVAjfnm0GI1V6ZHiGjq4HNH9xiA.png', 'name': 'Les Films Velvet', 'origin_country': 'FR'}, {'id': 88231, 'logo_path': '/hVx90I5BEktosw4N9AneIFwmjeg.png', 'name': 'Snowglobe', 'origin_country': 'DK'}], 'production_countries': [{'iso_3166_1': 'BE', 'name': 'Belgium'}, {'iso_3166_1': 'DK', 'name': 'Denmark'}, {'iso_3166_1': 'FR', 'name': 'France'}, {'iso_3166_1': 'MA', 'name': 'Morocco'}, {'iso_3166_1': 'NL', 'name': 'Netherlands'}, {'iso_3166_1': 'NO', 'name': 'Norway'}, {'iso_3166_1': 'SE', 'name': 'Sweden'}], 'release_date': '2024-12-18', 'revenue': 0, 'runtime': 102, 'spoken_languages': [{'english_name': 'Arabic', 'iso_639_1': 'ar', 'name': 'العربية'}], 'status': 'Released', 'tagline': '', 'title': 'Everybody Loves Touda', 'video': False, 'vote_average': 7.3, 'vote_count': 3}
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 {'adult': False, 'backdrop_path': '/gUfQhm8yW3m7LK8vaCqAs9g5Jdm.jpg', 'belongs_to_collection': None, 'budget': 0, 'genres': [{'id': 18, 'name': 'Drama'}], 'homepage': '', 'id': 1212337, 'imdb_id': 'tt29315015', 'origin_country': ['GB'], 'original_language': 'en', 'original_title': 'September Says', 'overview': 'When September is suspended from school, her sister July begins to assert her own independence. Tension in the family builds on holiday Ireland as a series of surreal encounters test the them all to their limit.', 'popularity': 0.987, 'poster_path': '/aVGF6uNJMzGQbz2X5gOhGFiaYAI.jpg', 'production_companies': [{'id': 288, 'logo_path': '/aW0IpM9d4Zjj978EqgDVSxXXhTj.png', 'name': 'BBC Film', 'origin_country': 'GB'}, {'id': 3353, 'logo_path': '/qv2v9HaStUTRjqonODM29YG0oFX.png', 'name': 'Element Pictures', 'origin_country': 'IE'}, {'id': 214894, 'logo_path': None, 'name': 'Sackville Film and Television Productions', 'origin_country': 'IE'}, {'id': 214895, 'logo_path': None, 'name': 'Crybaby Productions', 'origin_country': 'GB'}, {'id': 214896, 'logo_path': None, 'name': 'MFP', 'origin_country': 'DE'}], 'production_countries': [{'iso_3166_1': 'DE', 'name': 'Germany'}, {'iso_3166_1': 'IE', 'name': 'Ireland'}, {'iso_3166_1': 'GB', 'name': 'United Kingdom'}], 'release_date': '2025-02-19', 'revenue': 0, 'runtime': 100, 'spoken_languages': [{'english_name': 'English', 'iso_639_1': 'en', 'name': 'English'}], 'status': 'Released', 'tagline': '', 'title': 'September Says', 'video': False, 'vote_average': 6.0, 'vote_count': 3}
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      NaN
4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      NaN
5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      NaN

### TODO: Embed metadata for new titles

In [498]:
from vector_search.vector_search import MovieEmbedder
embedding_model = MovieEmbedder(movies_with_metadata)
embedding_model.prepare_text()

INFO:sentence_transformers.SentenceTransformer:Use pytorch device_name: cpu
INFO:sentence_transformers.SentenceTransformer:Load pretrained SentenceTransformer: sentence-transformers/all-mpnet-base-v2

Skipping embedding for nan - id is nan
Skipping embedding for nan - id is nan
Skipping embedding for nan - id is nan

In [501]:
print(movies_with_metadata.text_to_embed[0])

This is a Action, Crime, Drama film. Plot: Driven by tragedy, billionaire Bruce Wayne dedicates his life to
uncovering and defeating the corruption that plagues his home, Gotham City.  Unable to work within the system, he
instead creates a new identity, a symbol of fear for the criminal underworld - The Batman. Important themes
include: martial arts, undercover, loss of loved one, secret identity, crime fighter, superhero, based on comic,
rivalry, ninja, vigilante, tragic hero, super power, haunted by the past, evil doctor, master villain, unfulfilled
love, inspirational. It is directed by Christopher Nolan and stars Christian Bale, Michael Caine, Liam Neeson,
Katie Holmes, Gary Oldman. The movie has a rating of 7.711 based on 21297 reviews. A reviewer said: "‘Batman
Begins’ is a strong introduction to the Batman thanks to the magnificent cast and a superb score by Zimmer and
Newton Howard. 9/10" A reviewer said: "It was a nice change to see for a batman series of movies that were going
down hill. This movie was ok but at least it's not as bad as the ones that were being made before this." A reviewer
said: "A very self-involved and glum Batman. Not my favourite. Once we finally get to Batman being Batman it's a
cool movie." A reviewer said: "i'm beginning to think people only say a movie is good because of it being long and
having a good camera. to me the only highlight was cillian murphy's performance. the rest of this was just some
dumb, boring trek." A reviewer said: "**Batman Begins opened the door for the new age of superhero cinema with its
realistic, grounded approach and excellent quality.**    Many may not realize the groundbreaking impact Batman
Begins had on the superhero genre. While Spider-man and X-Men were popular films, many still rejected comic book
films as only for kids. Incredibly cheesy films like Catwoman and Batman + Robin didn’t help make the more grown-up
audiences have much faith in the genre." A reviewer said: "Christopher Nolan and Christian Bale are at the top of
their games with this enthralling interpretation of just how "Batman" came to be. "Bruce", the young sone of the
billionaire "Wayne" family finds himself unexpectedly orphaned and is soon aimlessly bumming his way around Asia.
It's when he encounters "Ducard" (Liam Neeson) and is lured high into the Himalayan mountains that he is set to
training by the legendary Ra's Al Ghul (Ken Watanabe) so that he can join the "League of Shadows" - an uniquely
skilled ninja-esque group of elite warriors." A reviewer said: "Christopher Nolan's "Batman Begins" shows us
exactly how Bruce Wayne (Christian Bale) transforms into the caped crusader we all know and love, Batman.
Admittedly like many others, even though this is the first entry in the Dark Knight Trilogy, I watched it is as my
last one, and that is due to me not even knowing of it's existence, which is thanks to it being heavily
overshadowed by the critically acclaimed sequel, "The Dark Knight."    Batman Begins has a simple plot to follow
full of twists. A young Bruce Wayne travels to the Far East, where he's trained in the martial arts by Henri Ducard
(Liam Neeson), a member of the mysterious League of Shadows." A reviewer said: "It's not who I am underneath, but
what I do that defines me. Bruce Wayne is constantly tortured by his childhood memories when he witnessed his
parents being murdered. Taken under the wing of The League Of Shadows, a deadly ninja assassin army devoted to
erasing crime with their own brand of harsh justice."

### TODO: Fetch ratings for underrated titles if applicable

#### Dependencies: need to be able to query from table, but will migrate to PostgreSQL after this anyway.

In [481]:
raise NotImplementedError

NotImplementedError:

### TODO: Save to PostgreSQL DB

In [11]:
# # enriched_new_movies = enriched_new_movies.where(pd.notna(enriched_new_movies), None)
# save_all_to_db(cinemas_df=cinemas_df,
#                movies_df=enriched_new_movies,
#                screenings_df=screenings_df)