### Pipeline, step by step

In [1]:
import sys
import os
sys.path.append(os.getcwd())

import logging
import pandas as pd
from data_pipelines.filmladder import ScreeningScraper, ImdbIdScraper, RedirectUrlScraper
from data_pipelines.letterboxd import TmdbIdScraper
from data_models.helpers import extract_unique_movies
from backend.data_models.helpers import process_cinemas, process_screenings
from backend.data_models.db import save_all_to_db
from rich import print

pd.options.display.max_rows = 100
pd.set_option('display.max_colwidth', None)
%load_ext autoreload
%autoreload 2

logging.basicConfig(level=logging.INFO)

### Collect screenings

In [2]:
logging.info("Starting daily data pipeline...")

# 1️⃣ Scrape Filmladder (returns two DataFrames)
screening_scraper = ScreeningScraper()
screenings_df, cinemas_df = await screening_scraper.run()

INFO:root:Starting daily data pipeline...

Cache hit for https://www.filmladder.nl/amsterdam/bioscopen - (scraper:907656650dfa9da03fb88fd6a2bd3a01)

### Remove duplicate screenings and process cinemas

In [3]:
# 2️⃣ Remove duplicates (imax, 2d, etc), add unique ids
screenings_df = process_screenings(screenings_df)
cinemas_df = process_cinemas(cinemas_df)

### Fetch ticket destination url

In [4]:
redirect_scraper = RedirectUrlScraper(cache_expiry=3600*24*7)
screenings_df = await redirect_scraper.run(screenings_df.iloc[:50])

# TODO: SAVE SCREENINGS NOW

Cache hit for https://www.filmladder.nl/kaartjes/1209279316 - (scraper:8a4634d450354792c18c927fba4c425c)
Cache hit for https://www.filmladder.nl/kaartjes/1209279621 - (scraper:0c7be953bf61e5d0460db2241073ae00)
Cache hit for https://www.filmladder.nl/kaartjes/1209393920 - (scraper:5cbf239fd6643ff72ad64a9a221dd42b)
Cache hit for https://www.filmladder.nl/kaartjes/1209434694 - (scraper:7dc0f63286cbd836cf89d7164e0c824a)
Cache hit for https://www.filmladder.nl/kaartjes/1209326554 - (scraper:1e6b317009229d56d6e1a3a4ac67485c)
Cache hit for https://www.filmladder.nl/kaartjes/1209400945 - (scraper:a2854733821f35a15cae4ca051d9c61a)
Cache hit for https://www.filmladder.nl/kaartjes/1209430223 - (scraper:c40da1336f8bd9b85f7e98af4745da28)
Cache hit for https://www.filmladder.nl/kaartjes/1209430303 - (scraper:b9300a7ebefa66129fdce2323f0a3168)
Cache hit for https://www.filmladder.nl/kaartjes/1209430885 - (scraper:1599a63816a247077a91ffd7b887701e)
Cache hit for https://www.filmladder.nl/kaartjes/1209431451 - (scraper:b686b1649dc26ace23691f9f66cf22b9)
Cache hit for https://www.filmladder.nl/kaartjes/1209431877 - (scraper:b92caaf84c33c90721161a5e5c2d477c)
Cache hit for https://www.filmladder.nl/kaartjes/1209432237 - (scraper:9631a4ad56ceb4681ea67ed147c7d5b8)
Cache hit for https://www.filmladder.nl/kaartjes/1209432794 - (scraper:aa25f3be389d66d5f575ce3ef4660e55)
Cache hit for https://www.filmladder.nl/kaartjes/1209433062 - (scraper:35ff5817812065fd35f2e99b00a0b3f1)
Cache hit for https://www.filmladder.nl/kaartjes/1209433572 - (scraper:78c38b5331bd4f0d610e99d0c4805789)
Cache hit for https://www.filmladder.nl/kaartjes/1209433908 - (scraper:3c80bb70715ca9cccaf1ca63d27ad277)
Cache hit for https://www.filmladder.nl/kaartjes/1209430409 - (scraper:815a8ee80c686450fb7029f3d1c0cbfc)
Cache hit for https://www.filmladder.nl/kaartjes/1209431425 - (scraper:9bf2e8c3ad73405198c122459e3f6de6)
Cache hit for https://www.filmladder.nl/kaartjes/1209432545 - (scraper:fa9642355b75c60f80cc26b830e600c5)
Cache hit for https://www.filmladder.nl/kaartjes/1209433266 - (scraper:a57e29434b7c653b65063bab083d787e)
Cache hit for https://www.filmladder.nl/kaartjes/1209434269 - (scraper:d126b23a6ec90223e94cb5365177263d)
Cache hit for https://www.filmladder.nl/kaartjes/1209430305 - (scraper:885795ade3da156c7448e5f5724e048e)
Cache hit for https://www.filmladder.nl/kaartjes/1209432246 - (scraper:5934d8751361b3dde0a298983a484a53)
Cache hit for https://www.filmladder.nl/kaartjes/1209433238 - (scraper:e8840eedf1828397102fd45fadec51e7)
Cache hit for https://www.filmladder.nl/kaartjes/1209430274 - (scraper:c1f22442338561c7313f937b8480a8f2)
Cache hit for https://www.filmladder.nl/kaartjes/1209430355 - (scraper:6369bfdd1f4e94c5ece43341e3ef86e4)
Cache hit for https://www.filmladder.nl/kaartjes/1209430894 - (scraper:a9b1433252b4f79399edf75a131876c3)
Cache hit for https://www.filmladder.nl/kaartjes/1209431737 - (scraper:de85af1ff02a974956cbc0034f743a65)
Cache hit for https://www.filmladder.nl/kaartjes/1209432066 - (scraper:4ffbc3b7d9fb73b3bb15975d291dabde)
Cache hit for https://www.filmladder.nl/kaartjes/1209432708 - (scraper:c88732fcbc0d115a9d76c8fe50b0a8a6)
Cache hit for https://www.filmladder.nl/kaartjes/1209432972 - (scraper:eeab65d31c8b5e842aec2a5f1105dd4c)
Cache hit for https://www.filmladder.nl/kaartjes/1209433078 - (scraper:a3697f9ac594a7b61a7146938fa7c407)
Cache hit for https://www.filmladder.nl/kaartjes/1209433408 - (scraper:f78f8bdc4cb85c0174e953f7eab39e19)
Cache hit for https://www.filmladder.nl/kaartjes/1209433760 - (scraper:64e3306779fcec70f398ee314f8a05de)
Cache hit for https://www.filmladder.nl/kaartjes/1209430184 - (scraper:a7d53f04d901ea4bdd3bdcb4278bb57c)
Cache hit for https://www.filmladder.nl/kaartjes/1209430657 - (scraper:93dbc9bb94ae9a26efebb668b50755e4)
Cache hit for https://www.filmladder.nl/kaartjes/1209430276 - (scraper:6dd0be8636fb3eaac1d5b50476b0e2c4)
Cache hit for https://www.filmladder.nl/kaartjes/1209431122 - (scraper:5ae3daef2e3a115efc62601c2af77c7f)
Cache hit for https://www.filmladder.nl/kaartjes/1209432095 - (scraper:b764f56f05655805d6add2fc09934780)
Cache hit for https://www.filmladder.nl/kaartjes/1209433008 - (scraper:0635ca698c20729213f9f233e2aba851)
Cache hit for https://www.filmladder.nl/kaartjes/1209433794 - (scraper:50c334a38b664611768a4ee82caab46c)
Cache hit for https://www.filmladder.nl/kaartjes/1209434202 - (scraper:3edcf6994b7848fd007d7c9b103102e5)
Cache hit for https://www.filmladder.nl/kaartjes/1209430219 - (scraper:50ba3485cfa2cca5e756c49b2500aa69)
Cache hit for https://www.filmladder.nl/kaartjes/1209430268 - (scraper:1629f4b72c597c0c0417bad33001944b)
Cache hit for https://www.filmladder.nl/kaartjes/1209430308 - (scraper:e84da194a8d39f4dcb34d5a214e10709)
Cache hit for https://www.filmladder.nl/kaartjes/1209430384 - (scraper:05fc3a02ce11d7cbc2866f2f30c4daec)
Cache hit for https://www.filmladder.nl/kaartjes/1209430640 - (scraper:ae210b2bb0c079ed2c9177b3f8ad7094)
Cache hit for https://www.filmladder.nl/kaartjes/1209430906 - (scraper:33d35537af7d9fbae66ed95c706e93d1)
Cache hit for https://www.filmladder.nl/kaartjes/1209431125 - (scraper:9b8504f7cef2130c6504cf20b5c47241)
Cache hit for https://www.filmladder.nl/kaartjes/1209431867 - (scraper:4e3b301258d97125da737631d39a200e)

### Extract unique titles from screenings, then visit each page to fetch corresponding IMDB ID

In [5]:
scraped_movies = extract_unique_movies(screenings_df)
imdb_id_scraper = ImdbIdScraper(cache_expiry=3600*24*7)
scraped_movies_with_id = await imdb_id_scraper.run(scraped_movies)

Cache hit for https://www.filmladder.nl/film/a-complete-unknown-2024-419175/popup/amsterdam - (scraper:91f7b4a1e99b6cc124fc88f4dad9557b)
Cache hit for https://www.filmladder.nl/film/parthenope-2024/popup/amsterdam - (scraper:a3ff89eeac35c47b9084b296b79a819f)
Cache hit for https://www.filmladder.nl/film/hard-truths-2024/popup/amsterdam - (scraper:8f700edacb77cf28b18bd9ccb4ab5453)
Cache hit for https://www.filmladder.nl/film/fiore-mio-2024/popup/amsterdam - (scraper:15f3a80ad34d7e40f91704ee5a7ed1ed)
Cache hit for https://www.filmladder.nl/film/all-we-imagine-as-light-2024/popup/amsterdam - (scraper:bea0533a887998a78b0dd2b3b5bb16a7)
Cache hit for https://www.filmladder.nl/film/anora-2024/popup/amsterdam - (scraper:d6f8c7e17508b7af1e628ee80bd2b6fc)
Cache hit for https://www.filmladder.nl/film/bridget-jones-mad-about-the-boy-2025/popup/amsterdam - (scraper:807d3cd1d86728f42e7711bb0c2595b1)
Cache hit for https://www.filmladder.nl/film/en-fanfare-2024/popup/amsterdam - (scraper:7847ddd6112440b2cfb98c38d0ee36da)
Cache hit for https://www.filmladder.nl/film/everybody-loves-touda-2024/popup/amsterdam - (scraper:b6cc1ba26b8aec5c177d241e497e7888)
Cache hit for https://www.filmladder.nl/film/i-m-still-here-2024/popup/amsterdam - (scraper:b5f521c148acb6984a011603775c9ce2)

### Use the fetched IMDB ID as a look up for which titles are not yet in the db and consequently, new

In [6]:
from data_models.db import get_new_movies
pd.set_option('display.width', 1000)
# TODO: CHANGE THIS TO FETCH NEW TITLES BASED ON fl_slug
new_movies = get_new_movies(scraped_movies=scraped_movies_with_id)

### Get identifiers from Letterboxd using imdb id if available (lb_id, tmdb_id, lb_film_slug)

In [7]:
# The following function visits the letterboxd page for each new film in the db and retrieves the lb slug and the TMDB id
tmdb_scraper = TmdbIdScraper(cache_expiry=3600*24*7)
new_movies_with_lb = await tmdb_scraper.run(new_movies)

/Users/ardsnijders/Documents/cineville_scraper/backend/data_pipelines/letterboxd.py:79: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[:, 'lb_url'] = df['imdb_id'].apply(lambda x: build_url(x))

Cache hit for https://letterboxd.com/imdb/tt23853982 - (scraper:ff30ce74c6ed0dce8acd8a20278b5630)
Cache hit for https://letterboxd.com/imdb/tt11891850 - (scraper:7b9cb9d59a205e7a5dc33ebb5dba6d40)
Cache hit for https://letterboxd.com/imdb/tt29283637 - (scraper:d9ca8cbb7fe244fd5b1e408091216336)
Cache hit for https://letterboxd.com/imdb/tt32086077 - (scraper:8bde59ee19a51575e93d79b49d127408)
Cache hit for https://letterboxd.com/imdb/tt11563598 - (scraper:2bd1f7eb18599b66e33928305984a7dd)
Cache hit for https://letterboxd.com/imdb/tt28607951 - (scraper:3dc8449c725c8ebfd850bd5690a53b75)

In [8]:
new_movies_with_lb

                  fl_title fl_year                                                                         fl_url                         fl_slug                               imdb_url     imdb_id                                  lb_url lb_film_id             lb_film_slug                             lb_poster_url  tmdb_id
0  all we imagine as light    2024    https://www.filmladder.nl/film/all-we-imagine-as-light-2024/popup/amsterdam    all-we-imagine-as-light-2024  https://www.imdb.com/title/tt32086077  tt32086077  https://letterboxd.com/imdb/tt32086077     833062  all-we-imagine-as-light  /film/all-we-imagine-as-light/image-150/   927547
1                fiore mio    2024                  https://www.filmladder.nl/film/fiore-mio-2024/popup/amsterdam                  fiore-mio-2024  https://www.imdb.com/title/tt29283637  tt29283637  https://letterboxd.com/imdb/tt29283637    1196386         a-flower-of-mine         /film/a-flower-of-mine/image-150/  1315134
2              hard truths    2024                https://www.filmladder.nl/film/hard-truths-2024/popup/amsterdam                hard-truths-2024  https://www.imdb.com/title/tt11891850  tt11891850  https://letterboxd.com/imdb/tt11891850     912810         hard-truths-2024         /film/hard-truths-2024/image-150/  1013154
3               parthenope    2024                 https://www.filmladder.nl/film/parthenope-2024/popup/amsterdam                 parthenope-2024  https://www.imdb.com/title/tt23853982  tt23853982  https://letterboxd.com/imdb/tt23853982     999589               parthenope               /film/parthenope/image-150/  1109255
4       a complete unknown       0  https://www.filmladder.nl/film/a-complete-unknown-2024-419175/popup/amsterdam  a-complete-unknown-2024-419175  https://www.imdb.com/title/tt11563598  tt11563598  https://letterboxd.com/imdb/tt11563598     586583       a-complete-unknown       /film/a-complete-unknown/image-150/   661539
5                    anora    2024                      https://www.filmladder.nl/film/anora-2024/popup/amsterdam                      anora-2024  https://www.imdb.com/title/tt28607951  tt28607951  https://letterboxd.com/imdb/tt28607951     959540                    anora                    /film/anora/image-150/  1064213

### Collect Metadata from TMDB using tmdb_id (movie_info, movie_keywords, movie_reviews)

In [9]:
from data_pipelines.tmdb import TMDBMetadataCollector
metadata_collector = TMDBMetadataCollector(cache_expiry=3600*24*7)

#TODO: FIX DUPLICATE CREATION IN  THIS FUNCTION
movies_with_metadata = await metadata_collector.run(df=new_movies_with_lb)

cache hit for tmdb id 661539 - (tmdb:661539)
cache hit for tmdb id 1315134 - (tmdb:1315134)
cache hit for tmdb id 1013154 - (tmdb:1013154)
cache hit for tmdb id 1064213 - (tmdb:1064213)
cache hit for tmdb id 1109255 - (tmdb:1109255)
cache hit for tmdb id 927547 - (tmdb:927547)

### TODO: Embed metadata for new titles

In [10]:
from vector_search.vector_search import MovieEmbedder
embedding_model = MovieEmbedder()
movies_with_prompts = embedding_model.prepare_text(movies_with_metadata)
movies_with_embeddings = embedding_model.generate_embeddings(movies_with_prompts)
# TODO fix tqdm progress update for generate embeddings
# TODO figure out why this sometimes breaks? i.e. lots of duplicate titles being returned

INFO:sentence_transformers.SentenceTransformer:Use pytorch device_name: cpu
INFO:sentence_transformers.SentenceTransformer:Load pretrained SentenceTransformer: sentence-transformers/all-mpnet-base-v2
Embedding movies:   0%|          | 0/6 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Embedding movies:  33%|███▎      | 2/6 [00:01<00:03,  1.12it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Embedding movies:  50%|█████     | 3/6 [00:01<00:01,  1.65it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Embedding movies:  67%|██████▋   | 4/6 [00:02<00:01,  1.86it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Embedding movies:  83%|████████▎ | 5/6 [00:02<00:00,  2.26it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Embedding movies: 100%|██████████| 6/6 [00:03<00:00,  2.18it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

Embedding movies: 100%|██████████| 6/6 [00:03<00:00,  1.64it/s]

### TODO: Fetch ratings for underrated titles if applicable

#### Dependencies: need to be able to query from table, but will migrate to PostgreSQL after this anyway.

In [11]:
raise NotImplementedError

NotImplementedError:

### TODO: Save to PostgreSQL DB

In [12]:
screenings_df.columns

for column in screenings_df.columns:
    if column != 'screening_id':
        screenings_df[column] = screenings_df[column].astype(str)

In [13]:
screenings_df

   fl_cinema_name                          fl_title fl_year           fl_show_datetime                                  fl_ticket_url fl_rating                                                                               fl_url                               fl_slug                                                                                          fl_poster_url  screening_id fl_cinema_id                                                    redirect_url
0     bijlmerbios           all we imagine as light    2024  2025-03-22 21:00:00+01:00  https://www.filmladder.nl/kaartjes/1209279621      7.1★          https://www.filmladder.nl/film/all-we-imagine-as-light-2024/popup/amsterdam          all-we-imagine-as-light-2024  https://assets.filmladder.nl/uploads/depot_image/asset/001/055/233/1055233/small_c206909efbc087ff.jpg    1209279621   cd51b85716                                                            None
1     bijlmerbios                         fiore mio    2024  2025-03-22 19:00:00+01:00  https://www.filmladder.nl/kaartjes/1209279316      6.9★                        https://www.filmladder.nl/film/fiore-mio-2024/popup/amsterdam                        fiore-mio-2024  https://assets.filmladder.nl/uploads/depot_image/asset/001/055/429/1055429/small_cb6e807494356495.jpg    1209279316   cd51b85716  https://www.cineville.nl/films/kaartjes/shows/2757924/redirect
2     bijlmerbios                         fiore mio    2024  2025-03-26 19:45:00+01:00  https://www.filmladder.nl/kaartjes/1209393920      6.9★                        https://www.filmladder.nl/film/fiore-mio-2024/popup/amsterdam                        fiore-mio-2024  https://assets.filmladder.nl/uploads/depot_image/asset/001/055/429/1055429/small_cb6e807494356495.jpg    1209393920   cd51b85716  https://www.cineville.nl/films/kaartjes/shows/2764439/redirect
3     bijlmerbios                       hard truths    2024  2025-03-23 15:30:00+01:00  https://www.filmladder.nl/kaartjes/1209326554      7.3★                      https://www.filmladder.nl/film/hard-truths-2024/popup/amsterdam                      hard-truths-2024  https://assets.filmladder.nl/uploads/depot_image/asset/001/055/150/1055150/small_8705ecadb1839372.jpg    1209326554   cd51b85716  https://www.cineville.nl/films/kaartjes/shows/2757922/redirect
4     bijlmerbios                       hard truths    2024  2025-03-28 19:45:00+01:00  https://www.filmladder.nl/kaartjes/1209434694      7.3★                      https://www.filmladder.nl/film/hard-truths-2024/popup/amsterdam                      hard-truths-2024  https://assets.filmladder.nl/uploads/depot_image/asset/001/055/150/1055150/small_8705ecadb1839372.jpg    1209434694   cd51b85716  https://www.cineville.nl/films/kaartjes/shows/2764877/redirect
5     bijlmerbios                        parthenope    2024  2025-03-27 19:45:00+01:00  https://www.filmladder.nl/kaartjes/1209400945      6.6★                       https://www.filmladder.nl/film/parthenope-2024/popup/amsterdam                       parthenope-2024  https://assets.filmladder.nl/uploads/depot_image/asset/001/052/236/1052236/small_2a8480ba63c67473.jpg    1209400945   cd51b85716  https://www.cineville.nl/films/kaartjes/shows/2764876/redirect
6      cinecenter                a complete unknown    None  2025-03-22 13:10:00+01:00  https://www.filmladder.nl/kaartjes/1209430223      7.4★        https://www.filmladder.nl/film/a-complete-unknown-2024-419175/popup/amsterdam        a-complete-unknown-2024-419175  https://assets.filmladder.nl/uploads/depot_image/asset/001/055/409/1055409/small_5157a1ef23a27ab3.jpg    1209430223   0f979e20b9  https://www.cineville.nl/films/kaartjes/shows/2768182/redirect
7      cinecenter                a complete unknown    None  2025-03-22 18:10:00+01:00  https://www.filmladder.nl/kaartjes/1209430303      7.4★        https://www.filmladder.nl/film/a-complete-unknown-2024-419175/popup/amsterdam        a-complete-unknown-2024-419175  https://assets.filmladder.nl/uploads/depot_image/asset/001/055/409/1055409/small_5157a1ef23a27ab3.jpg    1209430303   0f979e20b9  https://www.cineville.nl/films/kaartjes/shows/2768180/redirect
8      cinecenter                a complete unknown    None  2025-03-23 13:35:00+01:00  https://www.filmladder.nl/kaartjes/1209430885      7.4★        https://www.filmladder.nl/film/a-complete-unknown-2024-419175/popup/amsterdam        a-complete-unknown-2024-419175  https://assets.filmladder.nl/uploads/depot_image/asset/001/055/409/1055409/small_5157a1ef23a27ab3.jpg    1209430885   0f979e20b9  https://www.cineville.nl/films/kaartjes/shows/2768131/redirect
9      cinecenter                a complete unknown    None  2025-03-23 19:30:00+01:00  https://www.filmladder.nl/kaartjes/1209431451      7.4★        https://www.filmladder.nl/film/a-complete-unknown-2024-419175/popup/amsterdam        a-complete-unknown-2024-419175  https://assets.filmladder.nl/uploads/depot_image/asset/001/055/409/1055409/small_5157a1ef23a27ab3.jpg    1209431451   0f979e20b9                                                            None
10     cinecenter                a complete unknown    None  2025-03-24 13:05:00+01:00  https://www.filmladder.nl/kaartjes/1209431877      7.4★        https://www.filmladder.nl/film/a-complete-unknown-2024-419175/popup/amsterdam        a-complete-unknown-2024-419175  https://assets.filmladder.nl/uploads/depot_image/asset/001/055/409/1055409/small_5157a1ef23a27ab3.jpg    1209431877   0f979e20b9  https://www.cineville.nl/films/kaartjes/shows/2768095/redirect
11     cinecenter                a complete unknown    None  2025-03-24 18:10:00+01:00  https://www.filmladder.nl/kaartjes/1209432237      7.4★        https://www.filmladder.nl/film/a-complete-unknown-2024-419175/popup/amsterdam        a-complete-unknown-2024-419175  https://assets.filmladder.nl/uploads/depot_image/asset/001/055/409/1055409/small_5157a1ef23a27ab3.jpg    1209432237   0f979e20b9  https://www.cineville.nl/films/kaartjes/shows/2768093/redirect
12     cinecenter                a complete unknown    None  2025-03-25 13:05:00+01:00  https://www.filmladder.nl/kaartjes/1209432794      7.4★        https://www.filmladder.nl/film/a-complete-unknown-2024-419175/popup/amsterdam        a-complete-unknown-2024-419175  https://assets.filmladder.nl/uploads/depot_image/asset/001/055/409/1055409/small_5157a1ef23a27ab3.jpg    1209432794   0f979e20b9  https://www.cineville.nl/films/kaartjes/shows/2768099/redirect
13     cinecenter                a complete unknown    None  2025-03-25 18:10:00+01:00  https://www.filmladder.nl/kaartjes/1209433062      7.4★        https://www.filmladder.nl/film/a-complete-unknown-2024-419175/popup/amsterdam        a-complete-unknown-2024-419175  https://assets.filmladder.nl/uploads/depot_image/asset/001/055/409/1055409/small_5157a1ef23a27ab3.jpg    1209433062   0f979e20b9  https://www.cineville.nl/films/kaartjes/shows/2768096/redirect
14     cinecenter                a complete unknown    None  2025-03-26 13:05:00+01:00  https://www.filmladder.nl/kaartjes/1209433572      7.4★        https://www.filmladder.nl/film/a-complete-unknown-2024-419175/popup/amsterdam        a-complete-unknown-2024-419175  https://assets.filmladder.nl/uploads/depot_image/asset/001/055/409/1055409/small_5157a1ef23a27ab3.jpg    1209433572   0f979e20b9  https://www.cineville.nl/films/kaartjes/shows/2768113/redirect
15     cinecenter                a complete unknown    None  2025-03-26 18:10:00+01:00  https://www.filmladder.nl/kaartjes/1209433908      7.4★        https://www.filmladder.nl/film/a-complete-unknown-2024-419175/popup/amsterdam        a-complete-unknown-2024-419175  https://assets.filmladder.nl/uploads/depot_image/asset/001/055/409/1055409/small_5157a1ef23a27ab3.jpg    1209433908   0f979e20b9  https://www.cineville.nl/films/kaartjes/shows/2768102/redirect
16     cinecenter                             anora    2024  2025-03-22 21:10:00+01:00  https://www.filmladder.nl/kaartjes/1209430409      7.6★                            https://www.filmladder.nl/film/anora-2024/popup/amsterdam                            anora-2024  https://assets.filmladder.nl/uploads/depot_image/asset/001/047/964/1047964/small_a17f3e7db139ccc5.jpg    1209430409   0f979e20b9  https://www.cineville.nl/films/kaartjes/shows/2768185/redirect
17     cinecenter                             anora    2024  2025-03-23 19:15:00+01:00  https://www.filmladder.nl/kaartjes/1209431425      7.6★                            https://www.filmladder.nl/film/anora-2024/popup/amsterdam                            anora-2024  https://assets.filmladder.nl/uploads/depot_image/asset/001/047/964/1047964/small_a17f3e7db139ccc5.jpg    1209431425   0f979e20b9  https://www.cineville.nl/films/kaartjes/shows/2768069/redirect
18     cinecenter                             anora    2024  2025-03-24 21:10:00+01:00  https://www.filmladder.nl/kaartjes/1209432545      7.6★                            https://www.filmladder.nl/film/anora-2024/popup/amsterdam                            anora-2024  https://assets.filmladder.nl/uploads/depot_image/asset/001/047/964/1047964/small_a17f3e7db139ccc5.jpg    1209432545   0f979e20b9  https://www.cineville.nl/films/kaartjes/shows/2768088/redirect
19     cinecenter                             anora    2024  2025-03-25 21:10:00+01:00  https://www.filmladder.nl/kaartjes/1209433266      7.6★                            https://www.filmladder.nl/film/anora-2024/popup/amsterdam                            anora-2024  https://assets.filmladder.nl/uploads/depot_image/asset/001/047/964/1047964/small_a17f3e7db139ccc5.jpg    1209433266   0f979e20b9  https://www.cineville.nl/films/kaartjes/shows/2768107/redirect
20     cinecenter                             anora    2024  2025-03-26 21:10:00+01:00  https://www.filmladder.nl/kaartjes/1209434269      7.6★                            https://www.filmladder.nl/film/anora-2024/popup/amsterdam                            anora-2024  https://assets.filmladder.nl/uploads/depot_image/asset/001/047/964/1047964/small_a17f3e7db139ccc5.jpg    1209434269   0f979e20b9                                                            None
21     cinecenter  bridget jones: mad about the boy    2025  2025-03-22 18:20:00+01:00  https://www.filmladder.nl/kaartjes/1209430305      6.7★  https://www.filmladder.nl/film/bridget-jones-mad-about-the-boy-2025/popup/amsterdam  bridget-jones-mad-about-the-boy-2025  https://assets.filmladder.nl/uploads/depot_image/asset/001/054/809/1054809/small_b6387bec24a50fe2.jpg    1209430305   0f979e20b9  https://www.cineville.nl/films/kaartjes/shows/2768171/redirect
22     cinecenter  bridget jones: mad about the boy    2025  2025-03-24 18:15:00+01:00  https://www.filmladder.nl/kaartjes/1209432246      6.7★  https://www.filmladder.nl/film/bridget-jones-mad-about-the-boy-2025/popup/amsterdam  bridget-jones-mad-about-the-boy-2025  https://assets.filmladder.nl/uploads/depot_image/asset/001/054/809/1054809/small_b6387bec24a50fe2.jpg    1209432246   0f979e20b9  https://www.cineville.nl/films/kaartjes/shows/2768147/redirect
23     cinecenter  bridget jones: mad about the boy    2025  2025-03-25 20:45:00+01:00  https://www.filmladder.nl/kaartjes/1209433238      6.7★  https://www.filmladder.nl/film/bridget-jones-mad-about-the-boy-2025/popup/amsterdam  bridget-jones-mad-about-the-boy-2025  https://assets.filmladder.nl/uploads/depot_image/asset/001/054/809/1054809/small_b6387bec24a50fe2.jpg    1209433238   0f979e20b9  https://www.cineville.nl/films/kaartjes/shows/2768109/redirect
24     cinecenter                        en fanfare    2024  2025-03-22 16:00:00+01:00  https://www.filmladder.nl/kaartjes/1209430274      7.5★                       https://www.filmladder.nl/film/en-fanfare-2024/popup/amsterdam                       en-fanfare-2024  https://assets.filmladder.nl/uploads/depot_image/asset/001/053/343/1053343/small_5cc969dcd19278b7.jpg    1209430274   0f979e20b9  https://www.cineville.nl/films/kaartjes/shows/2768181/redirect
25     cinecenter                        en fanfare    2024  2025-03-22 20:50:00+01:00  https://www.filmladder.nl/kaartjes/1209430355      7.5★                       https://www.filmladder.nl/film/en-fanfare-2024/popup/amsterdam                       en-fanfare-2024  https://assets.filmladder.nl/uploads/depot_image/asset/001/053/343/1053343/small_5cc969dcd19278b7.jpg    1209430355   0f979e20b9  https://www.cineville.nl/films/kaartjes/shows/2768172/redirect
26     cinecenter                        en fanfare    2024  2025-03-23 13:40:00+01:00  https://www.filmladder.nl/kaartjes/1209430894      7.5★                       https://www.filmladder.nl/film/en-fanfare-2024/popup/amsterdam                       en-fanfare-2024  https://assets.filmladder.nl/uploads/depot_image/asset/001/053/343/1053343/small_5cc969dcd19278b7.jpg    1209430894   0f979e20b9  https://www.cineville.nl/films/kaartjes/shows/2768060/redirect
27     cinecenter                        en fanfare    2024  2025-03-24 11:00:00+01:00  https://www.filmladder.nl/kaartjes/1209431737      7.5★                       https://www.filmladder.nl/film/en-fanfare-2024/popup/amsterdam                       en-fanfare-2024  https://assets.filmladder.nl/uploads/depot_image/asset/001/053/343/1053343/small_5cc969dcd19278b7.jpg    1209431737   0f979e20b9  https://www.cineville.nl/films/kaartjes/shows/2768087/redirect
28     cinecenter                        en fanfare    2024  2025-03-24 15:55:00+01:00  https://www.filmladder.nl/kaartjes/1209432066      7.5★                       https://www.filmladder.nl/film/en-fanfare-2024/popup/amsterdam                       en-fanfare-2024  https://assets.filmladder.nl/uploads/depot_image/asset/001/053/343/1053343/small_5cc969dcd19278b7.jpg    1209432066   0f979e20b9  https://www.cineville.nl/films/kaartjes/shows/2768094/redirect
29     cinecenter                        en fanfare    2024  2025-03-25 11:00:00+01:00  https://www.filmladder.nl/kaartjes/1209432708      7.5★                       https://www.filmladder.nl/film/en-fanfare-2024/popup/amsterdam                       en-fanfare-2024  https://assets.filmladder.nl/uploads/depot_image/asset/001/053/343/1053343/small_5cc969dcd19278b7.jpg    1209432708   0f979e20b9  https://www.cineville.nl/films/kaartjes/shows/2768106/redirect
30     cinecenter                        en fanfare    2024  2025-03-25 15:55:00+01:00  https://www.filmladder.nl/kaartjes/1209432972      7.5★                       https://www.filmladder.nl/film/en-fanfare-2024/popup/amsterdam                       en-fanfare-2024  https://assets.filmladder.nl/uploads/depot_image/asset/001/053/343/1053343/small_5cc969dcd19278b7.jpg    1209432972   0f979e20b9  https://www.cineville.nl/films/kaartjes/shows/2768098/redirect
31     cinecenter                        en fanfare    2024  2025-03-25 18:35:00+01:00  https://www.filmladder.nl/kaartjes/1209433078      7.5★                       https://www.filmladder.nl/film/en-fanfare-2024/popup/amsterdam                       en-fanfare-2024  https://assets.filmladder.nl/uploads/depot_image/asset/001/053/343/1053343/small_5cc969dcd19278b7.jpg    1209433078   0f979e20b9  https://www.cineville.nl/films/kaartjes/shows/2768108/redirect
32     cinecenter                        en fanfare    2024  2025-03-26 11:00:00+01:00  https://www.filmladder.nl/kaartjes/1209433408      7.5★                       https://www.filmladder.nl/film/en-fanfare-2024/popup/amsterdam                       en-fanfare-2024  https://assets.filmladder.nl/uploads/depot_image/asset/001/053/343/1053343/small_5cc969dcd19278b7.jpg    1209433408   0f979e20b9  https://www.cineville.nl/films/kaartjes/shows/2768117/redirect
33     cinecenter                        en fanfare    2024  2025-03-26 15:55:00+01:00  https://www.filmladder.nl/kaartjes/1209433760      7.5★                       https://www.filmladder.nl/film/en-fanfare-2024/popup/amsterdam                       en-fanfare-2024  https://assets.filmladder.nl/uploads/depot_image/asset/001/053/343/1053343/small_5cc969dcd19278b7.jpg    1209433760   0f979e20b9  https://www.cineville.nl/films/kaartjes/shows/2768112/redirect
34     cinecenter             everybody loves touda    2024  2025-03-22 11:00:00+01:00  https://www.filmladder.nl/kaartjes/1209430184      6.7★            https://www.filmladder.nl/film/everybody-loves-touda-2024/popup/amsterdam            everybody-loves-touda-2024  https://assets.filmladder.nl/uploads/depot_image/asset/001/056/618/1056618/small_43e632e5759ba3e8.jpg    1209430184   0f979e20b9  https://www.cineville.nl/films/kaartjes/shows/2768072/redirect
35     cinecenter             everybody loves touda    2024  2025-03-23 11:15:00+01:00  https://www.filmladder.nl/kaartjes/1209430657      6.7★            https://www.filmladder.nl/film/everybody-loves-touda-2024/popup/amsterdam            everybody-loves-touda-2024  https://assets.filmladder.nl/uploads/depot_image/asset/001/056/618/1056618/small_43e632e5759ba3e8.jpg    1209430657   0f979e20b9  https://www.cineville.nl/films/kaartjes/shows/2768071/redirect
36     cinecenter                       hard truths    2024  2025-03-22 16:05:00+01:00  https://www.filmladder.nl/kaartjes/1209430276      7.3★                      https://www.filmladder.nl/film/hard-truths-2024/popup/amsterdam                      hard-truths-2024  https://assets.filmladder.nl/uploads/depot_image/asset/001/055/150/1055150/small_8705ecadb1839372.jpg    1209430276   0f979e20b9  https://www.cineville.nl/films/kaartjes/shows/2768183/redirect
37     cinecenter                       hard truths    2024  2025-03-23 15:50:00+01:00  https://www.filmladder.nl/kaartjes/1209431122      7.3★                      https://www.filmladder.nl/film/hard-truths-2024/popup/amsterdam                      hard-truths-2024  https://assets.filmladder.nl/uploads/depot_image/asset/001/055/150/1055150/small_8705ecadb1839372.jpg    1209431122   0f979e20b9  https://www.cineville.nl/films/kaartjes/shows/2768165/redirect
38     cinecenter                       hard truths    2024  2025-03-24 16:05:00+01:00  https://www.filmladder.nl/kaartjes/1209432095      7.3★                      https://www.filmladder.nl/film/hard-truths-2024/popup/amsterdam                      hard-truths-2024  https://assets.filmladder.nl/uploads/depot_image/asset/001/055/150/1055150/small_8705ecadb1839372.jpg    1209432095   0f979e20b9  https://www.cineville.nl/films/kaartjes/shows/2768086/redirect
39     cinecenter                       hard truths    2024  2025-03-25 16:05:00+01:00  https://www.filmladder.nl/kaartjes/1209433008      7.3★                      https://www.filmladder.nl/film/hard-truths-2024/popup/amsterdam                      hard-truths-2024  https://assets.filmladder.nl/uploads/depot_image/asset/001/055/150/1055150/small_8705ecadb1839372.jpg    1209433008   0f979e20b9  https://www.cineville.nl/films/kaartjes/shows/2768110/redirect
40     cinecenter                       hard truths    2024  2025-03-26 16:05:00+01:00  https://www.filmladder.nl/kaartjes/1209433794      7.3★                      https://www.filmladder.nl/film/hard-truths-2024/popup/amsterdam                      hard-truths-2024  https://assets.filmladder.nl/uploads/depot_image/asset/001/055/150/1055150/small_8705ecadb1839372.jpg    1209433794   0f979e20b9  https://www.cineville.nl/films/kaartjes/shows/2768123/redirect
41     cinecenter                       hard truths    2024  2025-03-26 20:50:00+01:00  https://www.filmladder.nl/kaartjes/1209434202      7.3★                      https://www.filmladder.nl/film/hard-truths-2024/popup/amsterdam                      hard-truths-2024  https://assets.filmladder.nl/uploads/depot_image/asset/001/055/150/1055150/small_8705ecadb1839372.jpg    1209434202   0f979e20b9  https://www.cineville.nl/films/kaartjes/shows/2768119/redirect

In [15]:
# enriched_new_movies = enriched_new_movies.where(pd.notna(enriched_new_movies), None)
save_all_to_db(cinemas_df=cinemas_df,
               movies_df=movies_with_embeddings,
               screenings_df=screenings_df)

INFO:root:Starting to delete all records from screenings table...
INFO:root:Records deleted successfully.
INFO:root:Columns in DataFrame: Index(['fl_cinema_name', 'fl_title', 'fl_year', 'fl_show_datetime', 'fl_ticket_url', 'fl_rating', 'fl_url', 'fl_slug', 'fl_poster_url', 'screening_id', 'fl_cinema_id', 'redirect_url'], dtype='object')
INFO:root:First few records:   fl_cinema_name                 fl_title fl_year           fl_show_datetime                                  fl_ticket_url fl_rating                                                                       fl_url                       fl_slug                                                                                          fl_poster_url  screening_id fl_cinema_id                                                    redirect_url
0    bijlmerbios  all we imagine as light    2024  2025-03-22 21:00:00+01:00  https://www.filmladder.nl/kaartjes/1209279621      7.1★  https://www.filmladder.nl/film/all-we-imagine-as-light-2024/popup/amsterdam  all-we-imagine-as-light-2024  https://assets.filmladder.nl/uploads/depot_image/asset/001/055/233/1055233/small_c206909efbc087ff.jpg    1209279621   cd51b85716                                                            None
1    bijlmerbios                fiore mio    2024  2025-03-22 19:00:00+01:00  https://www.filmladder.nl/kaartjes/1209279316      6.9★                https://www.filmladder.nl/film/fiore-mio-2024/popup/amsterdam                fiore-mio-2024  https://assets.filmladder.nl/uploads/depot_image/asset/001/055/429/1055429/small_cb6e807494356495.jpg    1209279316   cd51b85716  https://www.cineville.nl/films/kaartjes/shows/2757924/redirect
2    bijlmerbios                fiore mio    2024  2025-03-26 19:45:00+01:00  https://www.filmladder.nl/kaartjes/1209393920      6.9★                https://www.filmladder.nl/film/fiore-mio-2024/popup/amsterdam                fiore-mio-2024  https://assets.filmladder.nl/uploads/depot_image/asset/001/055/429/1055429/small_cb6e807494356495.jpg    1209393920   cd51b85716  https://www.cineville.nl/films/kaartjes/shows/2764439/redirect
3    bijlmerbios              hard truths    2024  2025-03-23 15:30:00+01:00  https://www.filmladder.nl/kaartjes/1209326554      7.3★              https://www.filmladder.nl/film/hard-truths-2024/popup/amsterdam              hard-truths-2024  https://assets.filmladder.nl/uploads/depot_image/asset/001/055/150/1055150/small_8705ecadb1839372.jpg    1209326554   cd51b85716  https://www.cineville.nl/films/kaartjes/shows/2757922/redirect
4    bijlmerbios              hard truths    2024  2025-03-28 19:45:00+01:00  https://www.filmladder.nl/kaartjes/1209434694      7.3★              https://www.filmladder.nl/film/hard-truths-2024/popup/amsterdam              hard-truths-2024  https://assets.filmladder.nl/uploads/depot_image/asset/001/055/150/1055150/small_8705ecadb1839372.jpg    1209434694   cd51b85716  https://www.cineville.nl/films/kaartjes/shows/2764877/redirect
INFO:root:Inserting 50 records into screenings table...
INFO:root:Data inserted and committed successfully.
INFO:root:Session closed.